### ISSUE TITLE
Bug al abrir fichero de coordenadas

### ISSUE THREAD

**Issue by tonilogar** [tonilogar/ToolsPcot#2]
Al mostrar el fichero de coordenadas en el widget nos muestra una linea al final con ceros.

**Comment by Kalebros** [comment]
Es verdad, hay un bug y este es el aspecto que tiene
![bug_coordenadas](https://cloud.githubusercontent.com/assets/7171608/13334883/8935be6a-dc0e-11e5-8286-6aedddae3e30.png)

**Comment by Kalebros** [comment]
Este código puede ser de ayuda <script src="https://gist.github.com/Kalebros/2d148567cd9b81b151be.js"></script>

Aquí está el enlace: https://gist.github.com/Kalebros/2d148567cd9b81b151be

**Comment by Kalebros** [comment]
Corregido el bug en el commit 6562f935b104f7a5160eb7f7b7f2bab17ced464d ( [Commit](https://github.com/tonilogar/ToolsPcot/commit/6562f935b104f7a5160eb7f7b7f2bab17ced464d) )
