### ISSUE TITLE
[B-00] Se permiten signos de puntuacion en los identificadores de coordenadas

### ISSUE THREAD

**Issue by Kalebros** [tonilogar/ToolsPcot#4]
Puedes crear un identificador de coordenadas que contenga signos de puntuacion
![bug-00](https://cloud.githubusercontent.com/assets/7171608/13336423/29a72008-dc16-11e5-9254-ce41b7ded84b.png)

SUGERENCIA DE SOLUCIÓN: Añadir el código dentro de  ReaderCoordinatesBasico::checkListaIdentificadores()

**Comment by tonilogar** [comment]
Doy por terminado el método.
El usuario tendrá que escribir correctamente los identificadores, y de esta forma tampoco coarto el nombre que el usuario quiera utilizar.
